services:
  # База данных - запускается первой
  db:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ".env.db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5



  bot:
    build: .
    volumes:
      - .:/app
      - /app/.venv
    command: python3 -m main
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ".env"

volumes:
  pgdata: