version: 1
disable_existing_loggers: no

formatters:
  console_formatter_backend:
    (): app.logger.ConsoleFormatter
  file_formatter_backend:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console_handler_backend:
    class: logging.StreamHandler
    formatter: console_formatter_backend

  file_handler_backend:
    class: logging.handlers.RotatingFileHandler
    filename: logs/bot.log
    mode: a
    encoding: utf-8
    formatter: file_formatter_backend
    maxBytes: 10485760         # 10 MB
    backupCount: 3

root:
  level: INFO
  handlers: [ console_handler_backend, file_handler_backend ]

loggers:
  vpn_service:
    level: INFO
    propagate: no
    handlers: [ console_handler_backend, file_handler_backend ]
  uvicorn:
    level: INFO
    propagate: yes
